# Generated by Django 4.2.7 on 2023-11-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeeducationblock',
            name='uuid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
