# Generated by Django 4.2.5 on 2023-09-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='country',
            field=models.CharField(choices=[('RU', 'Russia'), ('KZ', 'Kazakhstan'), ('BY', 'Belarus'), ('UZ', 'Uzbekistan'), ('AZ', 'Azerbaijan'), ('GE', 'Georgia'), ('KG', 'Kyrgyzstan')], default='KZ', max_length=3),
        ),
    ]
