# Generated by Django 4.2.7 on 2023-11-27 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeworkexperienceblock',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience_blocks', to='hh.resume'),
        ),
    ]
