# Generated by Django 4.2.7 on 2023-11-24 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0002_resumeeducationblock_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeeducationblock',
            name='year_of_graduation',
            field=models.PositiveIntegerField(help_text='Please, use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
