# Generated by Django 4.2.7 on 2023-11-29 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0002_alter_resumeworkexperienceblock_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='visible',
            new_name='archived',
        ),
    ]
