# Generated by Django 4.2.5 on 2023-09-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0002_alter_jobposting_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='preferred_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
