# Generated by Django 4.2.7 on 2023-11-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0003_delete_product_rename_visible_jobposting_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
