# Generated by Django 4.2.5 on 2023-09-21 12:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0003_jobseekerprofile_preferred_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
