# Generated by Django 4.2.7 on 2023-11-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0004_alter_jobposting_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='archived',
            new_name='is_archived',
        ),
    ]
