# Generated by Django 4.2.7 on 2023-11-29 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0005_rename_archived_jobposting_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeToEmployerNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received', models.BooleanField(default=False)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_receivers', to=settings.AUTH_USER_MODEL)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='hh.jobposting')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='hh.resume')),
            ],
        ),
    ]
