# Generated by Django 4.2.7 on 2023-11-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0006_resumetoemployernotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumetoemployernotification',
            name='employer',
        ),
    ]
