# Generated by Django 4.2.7 on 2023-12-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0007_remove_resumetoemployernotification_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetoemployernotification',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
