# Generated by Django 4.2.7 on 2023-12-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0008_resumetoemployernotification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
